# Generated by Django 5.0.3 on 2024-03-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='complete',
        ),
    ]
